INSERT INTO items (id, level, type, name_cn, name_en, description, usage)
VALUES
    (3003, 4, 1, '赤金', 'Pure Gold', 'How much ore does it take to make such valuable gold bars? It doesn''t matter. What matters is that they''re yours.', 'A refined gold bar. Can be exchanged for a lot of LMD. 1x Pure Gold = 500 LMD (RIIC Trading Post).'),
    /**********************************************************************/
    /*                         # BATTLE RECORDS #                         */
    /**********************************************************************/
    (2001, 2, 2, '基础作战记录', 'Drill Battle Record', 'In such a hostile environment, every operation has the potential for a loss of life. We may be able to save more people if we are well prepared.
A video record of several battles.','A device that stores battle videos. Gives Operators a slight amount of EXP. Total EXP: 200.'),
    (2002, 3, 2, '初级作战记录', 'Frontline Battle Record', 'In such a hostile environment, every operation has the potential for a loss of life. We may be able to save more people if we are well prepared.
A video record of several battles, with detailed statistical analysis, plus 3 hours of additional materials and interviews.', 'A device that stores battle videos. Gives Operators a moderate amount of EXP. Total EXP: 400.'),
    (2003, 4, 2, '中级作战记录', 'Tactical Battle Record', 'In such a hostile environment, every operation has the potential for a loss of life. We may be able to save more people if we are well prepared.
A video record of several battles, plus the signature of the one who recorded them.', 'A device that stores battle videos. Gives Operators a significant amount of EXP. Total EXP: 1000.'),
    (2004, 5, 2, '高级作战记录', 'Strategic Battle Record', 'In such a hostile environment, every operation has the potential for a loss of life. We may be able to save more people if we are well prepared.
Comes with a collector''s edition, a HD version, an HD remastered version, an Enhanced edition, a Director''s cut edition, an Annual Gold edition...', 'A device that stores battle videos. Gives Operators a huge amount of EXP. Total EXP: 2000.'),
    /**********************************************************************/
    /*                           # CARBON 💀 #                            */
    /**********************************************************************/
    (3112, 2, 3, '碳', 'Carbon Stick', 'One of the necessary industrial materials, it can be used to produce a variety of polymers.', 'A carbon stick used for the facility development of Rhodes Island.'),
    (3113, 3, 3, '碳素', 'Carbon Brick', 'Light and highly pure, it possesses excellent workability, and is instrumental to the success of our operations.', 'A carbon brick used for the facility development of Rhodes Island.'),
    (3114, 4, 3, '碳素组', 'Carbon Pack', 'A large number of carbon bricks. Every one of them has a burning soul for modern industry.', 'A pack of carbon bricks used for the facility development of Rhodes Island.'),
    /**********************************************************************/
    /*                       # PROMOTION CHIPS #                          */
    /**********************************************************************/
    (3211, 2, 4, '先锋芯片', 'Vanguard Chip', 'A material obtained after hard training. It seems to be especially helpful for rookie Vanguard Operators.', 'A memory chip that records special trainings. Can be used to Promote Vanguard Operators.'),
    (3212, 3, 4, '先锋芯片组', 'Vanguard Chip Pack', 'A material obtained after hard training. It seems to be especially helpful for experienced Vanguard Operators.', 'A memory chip pack that records special trainings. Can be used to Promote Vanguard Operators.'),
    (3213, 4, 4, '先锋双芯片', 'Vanguard Dualchip', 'A material obtained after hard training. It seems to be especially helpful for veteran Vanguard Operators.', 'A dualchip that records special trainings. Can be used to Promote Vanguard Operators.'),
    (3221, 2, 4, '近卫芯片', 'Guard Chip', 'A material obtained after hard training. It seems to be especially helpful for rookie Guard Operators.', 'A memory chip that records special trainings. Can be used to Promote Guard Operators.'),
    (3222, 3, 4, '近卫芯片组', 'Guard Chip Pack', 'A material obtained after hard training. It seems to be especially helpful for experienced Guard Operators.', 'A memory chip pack that records special trainings. Can be used to Promote Guard Operators.'),
    (3223, 4, 4, '近卫双芯片', 'Guard Dualchip', 'A material obtained after hard training. It seems to be especially helpful for veteran Guard Operators.', 'A dualchip that records special trainings. Can be used to Promote Guard Operators.'),
    (3231, 2, 4, '重装芯片', 'Defender Chip', 'A material obtained after hard training. It seems to be especially helpful for rookie Defender Operators.', 'A memory chip that records special trainings. Can be used to Promote Defender Operators.'),
    (3232, 3, 4, '重装芯片组', 'Defender Chip Pack', 'A material obtained after hard training. It seems to be especially helpful for experienced Defender Operators.', 'A memory chip pack that records special trainings. Can be used to Promote Defender Operators.'),
    (3233, 4, 4, '重装双芯片', 'Defender Dualchip', 'A material obtained after hard training. It seems to be especially helpful for veteran Defender Operators.', 'A dualchip that records special trainings. Can be used to Promote Defender Operators.'),
    (3241, 2, 4, '狙击芯片', 'Sniper Chip', 'A material obtained after hard training. It seems to be especially helpful for rookie Sniper Operators.', 'A memory chip that records special trainings. Can be used to Promote Sniper Operators.'),
    (3242, 3, 4, '狙击芯片组', 'Sniper Chip Pack', 'A material obtained after hard training. It seems to be especially helpful for experienced Sniper Operators.', 'A memory chip pack that records special trainings. Can be used to Promote Sniper Operators.'),
    (3243, 4, 4, '狙击双芯片', 'Sniper Dualchip', 'A material obtained after hard training. It seems to be especially helpful for veteran Sniper Operators.', 'A dualchip that records special trainings. Can be used to Promote Sniper Operators.'),
    (3251, 2, 4, '术师芯片', 'Caster Chip', 'A material obtained after hard training. It seems to be especially helpful for rookie Caster Operators.', 'A memory chip that records special trainings. Can be used to Promote Caster Operators.'),
    (3252, 3, 4, '术师芯片组', 'Caster Chip Pack', 'A material obtained after hard training. It seems to be especially helpful for experienced Caster Operators.', 'A memory chip pack that records special trainings. Can be used to Promote Caster Operators.'),
    (3253, 4, 4, '术师双芯片', 'Caster Dualchip', 'A material obtained after hard training. It seems to be especially helpful for veteran Caster Operators.', 'A dualchip that records special trainings. Can be used to Promote Caster Operators.'),
    (3261, 2, 4, '医疗芯片', 'Medic Chip', 'A material obtained after hard training. It seems to be especially helpful for rookie Medic Operators.', 'A memory chip that records special trainings. Can be used to Promote Medic Operators.'),
    (3262, 3, 4, '医疗芯片组', 'Medic Chip Pack', 'A material obtained after hard training. It seems to be especially helpful for experienced Medic Operators.', 'A memory chip pack that records special trainings. Can be used to Promote Medic Operators.'),
    (3263, 4, 4, '医疗双芯片', 'Medic Dualchip', 'A material obtained after hard training. It seems to be especially helpful for veteran Medic Operators.', 'A dualchip that records special trainings. Can be used to Promote Medic Operators.'),
    (3271, 2, 4, '辅助芯片', 'Supporter Chip', 'A material obtained after hard training. It seems to be especially helpful for rookie Supporter Operators.', 'A memory chip that records special trainings. Can be used to Promote Supporter Operators.'),
    (3272, 3, 4, '辅助芯片组', 'Supporter Chip Pack', 'A material obtained after hard training. It seems to be especially helpful for experienced Supporter Operators.', 'A memory chip pack that records special trainings. Can be used to Promote Supporter Operators.'),
    (3273, 4, 4, '辅助双芯片', 'Supporter Dualchip', 'A material obtained after hard training. It seems to be especially helpful for veteran Supporter Operators.', 'A dualchip that records special trainings. Can be used to Promote Supporter Operators.'),
    (3281, 2, 4, '特种芯片', 'Specialist Chip', 'A material obtained after hard training. It seems to be especially helpful for rookie Specialist Operators.', 'A memory chip that records special trainings. Can be used to Promote Specialist Operators.'),
    (3282, 3, 4, '特种芯片组', 'Specialist Chip Pack', 'A material obtained after hard training. It seems to be especially helpful for experienced Specialist Operators.', 'A memory chip pack that records special trainings. Can be used to Promote Specialist Operators.'),
    (3283, 4, 4, '特种双芯片', 'Specialist Dualchip', 'A material obtained after hard training. It seems to be especially helpful for veteran Specialist Operators.', 'A dualchip that records special trainings. Can be used to Promote Specialist Operators.'),
    /**********************************************************************/
    /*                        # SKILL SUMMARIES #                         */
    /**********************************************************************/
    (3301, 2, 5, '技巧概要·卷1', 'Skill Summary - 1', 'It records entry-level skills needed by Operators. Even a dummy could master the techniques after a bit of study.', 'A book that records basic tactics. Can be used to upgrade Operator skills.'),
    (3302, 3, 5, '技巧概要·卷2', 'Skill Summary - 2', 'It records junior skills needed by Operators. It takes some time and effort to master them.', 'A book that records intermediate tactics. Can be used to upgrade Operator skills.'),
    (3303, 4, 5, '技巧概要·卷3', 'Skill Summary - 3', 'It records high level skills needed by Operators. It takes a depth of experience in relevant fields to understand them.', 'A book that records advanced tactics. Can be used to upgrade Operator skills.'),
    /**********************************************************************/
    /*                        # LEVEL-UP MATERIALS #                      */
    /**********************************************************************/
    (30011, 1, 6, '源岩', 'Orirock', 'Rich in organics, it is commonly seen in regions where Originium has completely volatilized. Compared to Originium, it is easier to exploit.', 'A rock mined from the ground. Can be used for a variety of upgrades and for production in the Factory.'),
    (30012, 2, 6, '固源岩', 'Orirock Cube', 'With numerous micropores, it is often used in the interlayer of armors as an adsorbent of the breakdown product of Originium gas.', 'A rock cube mined from the ground. Can be used for a variety of upgrades and for production in the Factory.'),
    (30013, 3, 6, '固源岩组', 'Orirock Cluster', 'Compressed from Orirock Cubes, it can be formed naturally. It is a fragile material, but industrial technology has made it possible to produce complete Orirock Clusters now. People often mistake it for an ordinary cluster of rocks.', 'A conglomerate rock mined from the ground. Can be used for a variety of upgrades and for production in the Factory.'),
    (30014, 4, 6, '提纯源岩', 'Orirock Concentration', 'This Orirock looks different from the raw material after the refinement process. It costs much more than other processing methods. Anyone who has seen the smooth cutting surface will be amazed. That must be the charm of combining nature with industry.', 'A refined matter produced with Orirock Cluster. Can be used for a variety of upgrades and the synthesis of Polymerization Preparation.'),
    (30021, 1, 6, '代糖', 'Sugar Substitute', 'It''s slightly sweet and possibly edible. It is also commonly used in chemical manufacturing.', 'Cheap sugar substitute produced by assembly line. Can be used for a variety of upgrades and for production in the Factory.'),
    (30022, 2, 6, '糖', 'Sugar', 'A more expensive sugar made from natural materials. Ahh, this taste... will surely put one in a great mood. However, it''s not for casual snacking.', 'A small amount of sugar produced by assembly line. Can be used for a variety of upgrades and for production in the Factory.'),
    (30023, 3, 6, '糖组', 'Sugar Pack', 'A calorie-rich sugar pack that''s highly sought after. Its weight never seems to meet the standards set for chemical manufacturing. The production line employees may have something to do with it.', 'A decent amount of sugar produced by assembly line. Can be used for a variety of upgrades and for production in the Factory.'),
    (30024, 4, 6, '糖聚块', 'Sugar Lump', 'A nice, finely processed sugar lump commonly used for potion production. Do not taste test it! This is not food and is not to be sold as food! EVER!', 'A large amount of sugar produced by assembly line. Can be used for a variety of upgrades and for production in the Factory.'),
    (30031, 1, 6, '酯原料', 'Ester', 'One of the most important materials in modern industry. Its appearance has lead to the development of many modern products. This one, of course, is only a raw material that has practical application.', 'Ester used in industrial production. Can be used for a variety of upgrades and for production in the Factory.'),
    (30032, 2, 6, '聚酸酯', 'Polyester', 'Although its is lacking in potency, it can still be used to produce some basic materials we need. It is also a common ingredient in some sustained-release drugs.', 'A small amount of polyester used in industrial production. Can be used for a variety of upgrades and for production in the Factory.'),
    (30033, 3, 6, '聚酸酯组', 'Polyester Pack', 'After a series of processes, it meets the standards and general needs of most products on the market. It can also be used to process some special materials.', 'A pack of polyester used in industrial production. Can be used for a variety of upgrades and for production in the Factory.'),
    (30034, 4, 6, '聚酸酯块', 'Polyester Lump', 'A refined material. As a product, it is mostly sold to organizations and research institutions that have extremely high raw material needs. It may become the basis of the next generation of materials.', 'A lump of polyester used in industrial production. Can be used for a variety of upgrades and for production in the Factory.'),
    (30041, 1, 6, '异铁碎片', 'Oriron Shard', 'A byproduct of massive metal processing. Its high plasticity and oxidation resistance make it a common material of smelting and phased processing.', 'A common industrial material. Can be used for a variety of upgrades and for production in the Factory.'),
    (30042, 2, 6, '异铁', 'Oriron', 'In a small number of inerting processes, Oriron Shards may have phase changed and polymerized into Oriron. It is generally thought that Oriron is relatively stable when it reaches this level.', 'A rare industrial material. Can be used for a variety of upgrades and for production in the Factory.'),
    (30043, 3, 6, '异铁组', 'Oriron Cluster', 'During the processing, influenced by very few unartificial factors, multiple Orirons may merge into this form by chance. Its hardness has decreased but its purity has increased.', 'A precious industrial material. Can be used for a variety of upgrades and for production in the Factory.'),
    (30044, 4, 6, '异铁块', 'Oriron Block', 'An Oriron block fused with multiple Oriron Clusters under extremely harsh conditions. As the most stable and rarest form of Oriron, it can be used in all manners of industrial production.', 'An expensive industrial material. Can be used for a variety of upgrades and the synthesis of Polymerization Preparation.'),
    (30051, 1, 6, '双酮', 'Diketon', 'A very small amount of Diketon. After reprocessing, Engineer Operators use solidification during chemical combination to bond other stable structures.', 'A very small amount of industrial organic compound. Can be used for a variety of upgrades and for production in the Factory.'),
    (30052, 2, 6, '酮凝集', 'Polyketon', 'A small amount of Polyketon preparation produced through a special process. Its closed molecular structure has changed much complicated processing into simple chemical reactions. Of course, certain technical support is still needed.', 'A small amount of industrial organic compound. Can be used for a variety of upgrades and for production in the Factory.'),
    (30053, 3, 6, '酮凝集组', 'Aketon', 'A modest amount of Aketon preparation produced through further dehydrocarbon processing. The preparation reacts with the non-oxygen molecules in the air, so Engineer Operators must be careful during processing to avoid waste.', 'A modest amount of industrial organic compound. Can be used for a variety of upgrades and for production in the Factory.'),
    (30054, 4, 6, '酮阵列', 'Keton Colloid', 'A large amount of unstable Keton preparation. As one of the advanced industrial materials, it is closely monitored by our Engineer Operators. Please be careful when handling.', 'A large amount of industrial organic compound. Can be used for a variety of upgrades and the synthesis of Polymerization Preparation.'),
    (30061, 1, 6, '破损装置', 'Damaged Device', 'A broken device that was embedded in the enemy''s weapons and armor. It got damaged during a fierce fight, but the components inside are still valuable.', 'A damaged mechanical device captured from Reunion. Can be used for a variety of upgrades and for production in the Factory.'),
    (30062, 2, 6, '装置', 'Device', 'A set of devices that are relatively complete with numerous valuable components. To make it portable and practical, almost every bit of space around the motherboard is in use.', 'An ordinary mechanical device captured from Reunion. Can be used for a variety of upgrades and for production in the Factory.'),
    (30063, 3, 6, '全新装置', 'Integrated Device', 'A set of brand new devices. By reproducing the structure of devices of the same type, the lack of space around the motherboard has been solved. The energy consumption, of course, has also become higher.', 'A brand new mechanical device captured from Reunion. Can be used for a variety of upgrades and for production in the Factory.'),
    (30064, 4, 6, '改量装置', 'Optimized Device', 'After undergoing a large number of private modifications, these devices have greatly expanded capacity, which improves performance at the cost of stability. From this, one can feel the dedication and perseverance from the makers.', 'An advanced mechanical device captured from Reunion. Can be used for a variety of upgrades and the synthesis of Bipolar Nanoflake.'),
    (30073, 3, 6, '扭转醇', 'Loxic Kohl', 'An outstanding chemical mediator. When in use, it often changes between two forms to store and release other materials. When it becomes liquid, some of its properties are the same as those of alcohol, which often leaves our Engineer Operators tipsy.', 'A flaky organic compound. Can be used for a variety of upgrades and for production in the Factory.'),
    (30074, 4, 6, '白马醇', 'White Horse Kohl', 'A product made from Loxic Kohl after fine processing. It was named after the company that discovered its production method. Experiments show that it tends to transform to a higher structure in abnormal environments.', 'A flaky organic compound. Can be used for a variety of upgrades and the synthesis of Bipolar Nanoflake.'),
    (30083, 3, 6, '轻锰矿', 'Manganese Ore', 'A metal that is used to produce a catalyst widely used in industries. As the reprocessing is complicated, accidents caused by nonstandard techniques do happen from time to time.', 'A metal ore used for metallurgy. Can be used for a variety of upgrades and for production in the Factory.'),
    (30084, 4, 6, '三水锰矿', 'Manganese Trihydrate', 'A precious metal which few companies are willing to use to produce industrial catalysts. The catalyst made from it, however, has an extremely long service life. It can be used repeatedly and even stripped and recycled, but the complicated processes have forced many companies to give up.', 'A metal ore used for metallurgy. Can be used for a variety of upgrades and the synthesis of D32 Steel.'),
    (30093, 3, 6, '研磨石', 'Grindstone', 'An important tool in component processing. It has stable properties, and will never explode, powderize, or crack.', 'A grindstone used to process weapon parts. Can be used for a variety of upgrades and for production in the Factory.'),
    (30094, 4, 6, '五水研磨石', 'Grindstone Pentahydrate', 'Compared to normal Grindstone, this tool has an even more stable structure. It is highly non-reactive.', 'An advanced grindstone used in the finish machining of weapon parts. Can be used for a variety of upgrades and the synthesis of D32 Steel.'),
    (30103, 3, 6, 'RMA70-12', 'RMA70-12', 'A mineral whose natural form is a complicated polyhedron. Its value for Originium Arts was known long before its industrial value.', 'A sensitive mineral with high conductivity. Can be used for a variety of upgrades and for production in the Factory.'),
    (30104, 4, 6, 'RMA70-24', 'RMA70-24', 'A mineral whose natural form is a complicated polyhedron. Found in 1024, it shows great industrial value that other minerals used for Originium Arts lack.', 'A highly sensitive mineral with outstanding conductivity. Can be used for a variety of upgrades and the synthesis of D32 Steel.'),
    (30115, 5, 6, '聚合剂', 'Polymerization Preparation', 'A material commonly used as an isolation coating for delicate equipment. Its bonding effect is strong enough to interrupt the volatilization of Originium.', 'A complicated liquid industrial product. Can be used for high level upgrades.'),
    (30125, 5, 6, '双极纳米片', 'Bipolar Nanoflake', 'A device that is sensitive to Originium within a certain range. It can significantly improve the sensitivity of nearby weapons and equipment to Originium, making them near vessels for Originium Arts.', 'The brainchild of modern science and industry. Can be used for high level upgrades.'),
    (30135, 5, 6, 'D32钢', 'D32 Steel', 'This material can deliver Originium Arts smoothly and its amazing hardness makes it impossible to penetrate. It will set a new standard for weapon materials.', 'An artificial metal that doesn''t exist in nature. Can be used for high level upgrades.'),
    (30145, 5, 6, '晶体电子单元', 'Crystalline Electronic Unit', 'A crystallization of Terra''s Originium technology. A symbol of Terra''s industrial modernization. From Originium Casting units to intercity network servers, their making all starts with inventions like these.', 'An expensive Originium industry product. Can be used for major upgrades.'),
    (30155, 5, 6, '烧结核凝晶', 'Nucleic Crystal Sinter', 'A material that possesses a molecular recognitive capacity under specific high-temperature conditions. Can selectively adsorb Originium when used as a reagent, allowing for precise handling of Originium materials, lower Originium device energy consumption, and the opening of further new possibilities.', 'A product of modern technology that requires the ultimate in industrial craft. Used in advanced strengthening projects.'),
    (31013, 3, 6, '凝胶', 'Coagulating Gel', 'An artificial material serendipitously born in the laboratory. It has excellent resistance to extreme temperatures, is lightweight, and is easy to process, making it ideal for use in high-tech projects.', 'A high-strength plastic material suitable. Can be used for a variety of upgrades and for synthesis projects in Factories.'),
    (31014, 4, 6, '聚合凝胶', 'Polymerized Gel', 'An artificial material created from a large number of experiments using coagulating gel as a base material. It can maintain its stability even in high-pressure environments, playing a key role in some high-tech projects.', 'An extremely high-strength plastic material. Can be used for a variety of upgrades.'),
    (31023, 3, 6, '炽合金', 'Incandescent Alloy', 'An alloy smelted from several rare Terran metals. Used to manufacture rare electronic components and circuit boards, it has become an indispensable material in the cutting-edge electronics industry.', 'A special alloy with a high melting point, commonly used in the electronics industry. Can be used for a variety of upgrades and for synthesis projects in Factories.'),
    (31024, 4, 6, '炽合金块', 'Incandescent Alloy Block', 'A product derived from further processing of incandescent alloy. After complicated industrial processing, the stability of its solid-liquid hybridization state at certain temperatures has been preserved. As a result, it has an irreplaceable role in product development in the cutting-edge electronics industry.', 'A rarely-produced alloy with a high melting point, commonly used in the electronics industry. Can be used for a variety of upgrades.'),
    (31033, 3, 6, '晶体元件', 'Crystalline Component', 'A raw industrial material made with the outer shell of an Originium crystal. A fundamental product in the modern Originium electronics industry.', 'An important Originium industry material. Can be used for a variety of upgrades. Can be manufactured and assembled into more advanced Originium electric components.'),
    (31034, 4, 6, '晶体电路', 'Crystalline Circuit', 'A core product in the modern Originium electronics industry. Found inside electronic goods far and wide throughout Terra''s nations. The mass application of crystalline circuitry is one more reminder of Terra''s industrial modernization.', 'An important Originium industry material. Can be used for a variety of upgrades. A fundamental part of manufacturing Originium crystal assemblies.'),
    (31043, 3, 6, '半自然溶剂', 'Semi-Synthetic Solvent', 'The product of a traditional solvent undergoing a modernization process, it demonstrates remarkably enhanced properties.', 'An active solvent with excellent physical characteristics, and good resistance to acids and bases. Can be used in a variety of upgrades.'),
    (31044, 4, 6, '精炼溶剂', 'Refined Solvent', 'A coating held together by high-molecule polymers. In addition to its baseline protective capabilities, it has also gained other special characteristics, of which heat resistance is but one of many.', 'A special coating made from a specific formulation process. Can be used for high level upgrades.'),
    (31053, 3, 6, '化合切削液', 'Compound Cutting Fluid', 'Provides lubrication and heat resistance during the refining process, which can further increase the rate at which metal products meet final quality specifications.', 'An industrial agent necessary for metal processing. Can be used for a variety of upgrades.'),
    (31054, 4, 6, '切削原液', 'Cutting Fluid Solution', 'A biologically stable stock solution. Precautions should be taken to avoid cross-contamination during storage.', 'A stock solution prepared from a variety of active solvents. Can be used for high level upgrades.'),
    (31063, 3, 6, '转质盐组', 'Transmuted Salt', 'The surface of this material has mutable characteristics, realizing results that were originally nearly impossible. CAUTION: industrial salt is not to be eaten under any circumstances.', 'A compound crystallization that has undergone low-tolerance refinement. Can be used in a variety of strengthening projects.'),
    (31064, 4, 6, '转质盐聚块', 'Transmuted Salt Agglomerate', 'A stable crystalline body, manufactured as a crystal blend within saturated solutions. Can provide materials with a diverse array of capabilities.', 'A compound crystal mass that has undergone high-tolerance refinement. Used in a variety of strengthening projects, and is a common material in synthetic items at factories.')

/* Upsert if the row is already in the database */
ON CONFLICT (id) DO UPDATE
    SET level   = excluded.level,
        type = excluded.type,
        name_cn = excluded.name_cn,
        name_en = excluded.name_en,
        description = excluded.description,
        usage = excluded.usage;
